cc_library(
    name = "greet",
    srcs = ["hello-greet.cc"],
    hdrs = ["hello-greet.h"],
)

cc_binary(
    name = "helloworld",
    srcs = ["hello-world.cc"],
    deps = [
        ":greet",
        "//lib:time",
    ],
)
###aaagefagsdadadfs